version: "3.1"

services:
  db:
    image: postgres:12
    restart: always
    ports:
      - 1234:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=humboldt
      - POSTGRES_PASSWORD=humboldt_1234
      - POSTGRES_DB=humboldt
      
volumes:
  postgres-data: